services:
  docs:
    image: anaesthesia_at_rch_local_docs
    container_name: anaesthesia_at_rch_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./anaesthesia_at_rch:/app/anaesthesia_at_rch:z
    ports:
      - '9000:9000'
    command: /start-docs
